import type { Event } from '@/types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Workshop de Design Thinking',
    description: 'Aprenda as bases do Design Thinking e aplique em seus projetos. Um workshop prático e interativo.',
    date: '2024-09-15',
    time: '14:00',
    locationType: 'Presencial',
    address: 'Rua das Palmeiras, 123, São Paulo, SP',
    category: 'Workshop',
    imageUrl: 'https://placehold.co/600x400',
    organizer: 'Inova Hub',
    slug: 'workshop-design-thinking',
  },
  {
    id: '2',
    title: 'Seminário sobre Inteligência Artificial',
    description: 'Explore o futuro da IA com especialistas renomados. Descubra as últimas tendências e aplicações.',
    date: '2024-10-05',
    time: '09:00',
    locationType: 'Online',
    onlineLink: 'https://zoom.us/j/1234567890',
    category: 'Seminário',
    imageUrl: 'https://placehold.co/600x400',
    organizer: 'Tech Conference BR',
    slug: 'seminario-ia',
  },
  {
    id: '3',
    title: 'Conferência Anual de Marketing Digital',
    description: 'O maior evento de marketing digital da América Latina. Palestras, networking e muito mais.',
    date: '2024-11-20',
    time: '10:00',
    locationType: 'Presencial',
    address: 'Centro de Convenções Expo Hall, Rio de Janeiro, RJ',
    category: 'Conferência',
    imageUrl: 'https://placehold.co/600x400',
    organizer: 'Marketing Pro',
    slug: 'conferencia-marketing-digital',
  },
  {
    id: '4',
    title: 'Happy Hour de Networking para Empreendedores',
    description: 'Conecte-se com outros empreendedores em um ambiente descontraído. Ótima oportunidade para fazer contatos.',
    date: '2024-09-28',
    time: '18:00',
    locationType: 'Presencial',
    address: 'Bar Conexão, Av. Principal, 789, Belo Horizonte, MG',
    category: 'Networking',
    imageUrl: 'https://placehold.co/600x400',
    organizer: 'Startup Connect',
    slug: 'happy-hour-networking',
  },
  {
    id: '5',
    title: 'Feira de Artesanato Local',
    description: 'Descubra talentos locais e apoie pequenos produtores. Música ao vivo e gastronomia.',
    date: '2024-10-12',
    time: '11:00',
    locationType: 'Presencial',
    address: 'Praça da Cultura, S/N, Curitiba, PR',
    category: 'Social',
    imageUrl: 'https://placehold.co/600x400',
    organizer: 'Prefeitura Local',
    slug: 'feira-artesanato',
  },
];
